# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoList' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoList
    pod 'Alamofire', '~> 3.1.2'
    pod 'SwiftyJSON'

  target 'TodoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
